receivers:
  otlp:
    protocols:
      grpc:
      http:
  postgresql:
    endpoint: "db:5432"
    username: "postgres"
    password: "suman123"
    databases:
      - "test"
  sqlquery:
    db_driver: "postgres"
    datasource: "host=db port=5432 user=postgres password=suman123 dbname=test sslmode=disable"
    queries:
      - query: "SELECT COUNT(*) AS user_count FROM users"
        metrics:
          - metric_name: "custom.postgres.user_count"
            value_column: "user_count"
            type: "gauge"

processors:
  batch:
  resourcedetection:
    detectors: [env, system]

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  clickhouse:
    endpoint: tcp://clickhouse:9000?dial_timeout=10s&compress=lz4
    database: signoz_traces
    username: default
    password: ""

service:
  pipelines:
    metrics:
      receivers: [otlp, postgresql, sqlquery]
      processors: [batch, resourcedetection]
      exporters: [prometheus, clickhouse]
    traces:
      receivers: [otlp]
      processors: [batch, resourcedetection]
      exporters: [clickhouse]
